### ISSUE TITLE
Login as a dashboard student, log out, log in as another dashboard student, repeat.

### ISSUE THREAD

**Issue by ksmontville** [yeatmanlab/roar-dashboard#865]
"Logging in as a roar student (if is a new student you should see Assent/Consent form and NOT click it). 
If it is not a new student check: 
 - they have their name on the top
 - they have on the dropdown menu the administration you created
 - if they have optional assignments, look for the switching to optional and check the tasks are there
 - the have the number of tasks assigned correctly
 - their grade is correct"

**Comment by ksmontville** [comment]
Unable to login as a new student without refreshing the page between authorizations.

Results in a generic "Insufficient permissions" error, and the error attached below.

![Image](https://github.com/user-attachments/assets/a9c0c35f-a367-470f-82a7-acc98176367e)

**Comment by maximilianoertel** [comment]
Can you please provide the credentials you used via Slack DM? Thanks

**Comment by maximilianoertel** [comment]
@ksmontville this should now be fixed – could you please retest and confirm before I close the ticket?

**Comment by ksmontville** [comment]
@maximilianoertel Unfortunately I am still receiving the same behavior as described in the issue report.

Is there any additional information that I can provide for debuggung?

**Comment by maximilianoertel** [comment]
Thanks for flagging – you should be good to go now to retest on the [PR environment](https://roar-staging--pr748-ref-318-query-compos-licip3pp.web.app/ )

**Comment by richford** [comment]
I just tested this and it worked! I moved the status to passing
